name: build-macos

on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
    branches:
      - master

jobs:
  build-and-test:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init
        run: chmod +x ./build.sh

      - name: Install NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Install .NET 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Install .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Install .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Build
        run: ./build.sh --target build

      - name: Run Tests
        run: ./build.sh --target tests --exclusive
